module.exports = {
  "extends": "airbnb-base",
  "rules": {
    "no-console": "off",
    "no-await-in-loop": "off",
    "no-constant-condition": "off",
    "no-param-reassign": "off",
    "no-restricted-syntax": "off",
    "no-underscore-dangle": "off",
    "no-case-declarations": "off",
    "no-continue": "off",
    "object-curly-newline": "off",
    "no-bitwise": "off",
    "no-else-return": "off",
    "no-plusplus": "off",
    "class-methods-use-this": "off",
    "no-labels": "off",
    "consistent-return": "off",
    "no-return-await": "off",
    "no-restricted-globals": "off",
    "radix": "off",
    "no-confusing-arrow": "off",
    "import/no-unresolved": "off",
    'max-len': ['error', 120, 2, {
      ignoreUrls: true,
      ignoreComments: false,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
    }],
    "quote-props": "off",
    "quotes": "off",
  },
};
